import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
// Remove or comment out the globals.css import if you cleared it completely
// import "./globals.css";
import '@/scss/styles.scss';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App', // We'll update this later
  description: 'Generated by create next app', // We'll update this later
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
